# syntax=docker/dockerfile:1

FROM node:16.17-slim
EXPOSE 8080
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json
RUN npm install

# start app
CMD ["npm", "run", "serve"]
