# Template file used by Flasgger. Methods and most models are defined in files in /api/.
swagger: "2.0"
produces:
  - "application/json"
info:
  title: "Backend API"
  version: "1.0"
  description: |
    A small and simple API for fetching data about Docker objects on the server. All operations in the API are safe and idempotent.

    This API is specifically designed for the associated frontend that visualizes the information provided by this API.

    Information about the Docker objects is accessed with Docker Python SDK from the Docker Engine whose socket is available for the application. The values returned by the API are similar to the values of Docker API. Some returned values have descriptions in method descriptions. The method used to generate this documentation does not support proper value descriptions or examples.

    Missing values are reported as empty strings, empty arrays, or as 0.

    The PSS value for a container is computed by inspecting the memory usage of the processes in the container. The PSS value is obtained from the shared host operating system running the containers. In order to this to work properly, the application must be run with privileges.

    The application is designed to be used only with Docker Linux containers. The application will not work as expected when run with Docker Windows containers.


    Notations:
    - All sizes and memory statistics are reported in bytes.
    - Times are reported with UNIX timestamps.

    This documentation is generated by Flasgger package.

definitions:
  Error:
    description: "Error object"
    type: "object"
    required: ["message"]
    properties:
      message:
        description: "The error message."
        type: "string"
    example:
      message: "Error message."
